cidr_name         = "10.0.0.0/16"
vpc_tag_name      = "Dev Vpc"
aws_profile       = "dev"
aws_region        = "us-east-1"
aws_subnet_count  = 3
my_ip             = "155.33.132.68/32"
my_ami            = "ami-0ec11aabfc8258659"
db_storage_size   = 20
db_instance_class = "db.t3.micro"
db_engine         = "mysql"
db_engine_version = "8.0.32"
db_name           = "csye6225"
db_username       = "csye6225"
db_password       = "csye*6225"
db_public_access  = false
db_multiaz        = false